name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  xgo:
    name: Cross build
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.15.3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Gather image information
        id: info
        run: |
          GIT_COMMIT=$(git describe --always)
          BUILD_DATE=$(date -u +%FT%TZ)
          echo ::set-output name=sha::${GIT_COMMIT}
          echo ::set-output name=created::${BUILD_DATE}

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: ${{ matrix.go_version }}
          dest: output
          prefix: sftpgo
          targets: linux/arm64,linux/ppc64le
          v: true
          x: false
          race: false
          ldflags: -s -w -X github.com/drakkan/sftpgo/version.commit=${{ steps.info.sha }} -X github.com/drakkan/sftpgo/version.date=${{ steps.info.created }}
          buildmode: default

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo-cross
          path: output

