name: CI

on:
  push:
  pull_request:

jobs:
  testfreebsd:
    name: Test on FreeBSD
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v0.1.2
        with:
          mem: 2048
          prepare: pkg install -y go git
          run: |
            pw useradd sftpgo
            chown -R sftpgo ../test-github-actions
            mkdir -p /tmp/env/{go,.cache,.config}
            chown -R sftpgo /tmp/env
            go env -w GOCACHE="/tmp/env/.cache/go-build"
            go env -w GOMODCACHE="/tmp/env/go/pkg/mod"
            go env -w GOPATH="/tmp/env/go"
            su -m sftpgo -c 'go build -ldflags "-s -w -X github.com/drakkan/sftpgo/version.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/version.date=`date -u +%FT%TZ`" -o sftpgo'
            su -m sftpgo -c 'go test -v -p 1 -timeout 10m ./... -coverprofile=coverage.txt -covermode=atomic'
            ./sftpgo --version