name: CI

on:
  push:
  pull_request:

jobs:
  testfreebsd:
    name: Test on FreeBSD
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v0.1.2
        with:
          mem: 2048
          prepare: pkg install -y go
          run: |
            pw useradd sftpgo
            chown -R sftpgo ../test-github-actions
            mkdir /root/.cache || true
            chown -R sftpgo /root/.cache
            su -m sftpgo -c 'go build -ldflags "-s -w" -o sftpgo'
            su -m sftpgo -c 'go test -v -p 1 -timeout 10m ./... -coverprofile=coverage.txt -covermode=atomic'